baseurl = "https://negli0.github.io"
title = "Around The Computer"
copyright = "Copyright &copy; 2018 - negli0"
canonifyurls = true
theme = "kiera"

paginate = 20

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
hasCJKLanguage = true 
googleAnalytics = "UA-118652153-1"
FootnoteReturnLinkContents = "↑"


[author]
	name = "Hiroki Watanabe"
	github = "negli0"
	gitlab = ""
	linkedin = ""
	facebook = ""
	twitter = "__nelio__"
	instagram = ""

[params]
	tagline = "A Technical Blog about Computer Science"
	logo = "/img/logo.jpg"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
	title = "All Posts"
    url = "/posts/"
    weight = 10
	description = "All Posts"

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
	title = "Category List"
    url = "/categories/"
    weight = 100
	description = "Category List"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
	title = "Tag List"
    url = "/tags/"
    weight = 150
	description = "Tag List"


[[resources]]
	src = "static/cv.pdf"

[taxonomies]
tag = "tags"
category = "categories"
