baseurl = "https://negli0.github.io"
title = "Around The Computer"
copyright = "Copyright &copy; 2018 - negli0"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
	name = "Hiroki Watanabe"
	github = "negli0"
	gitlab = ""
	linkedin = ""
	facebook = ""
	twitter = "__nelio__"
	instagram = ""

[params]
	tagline = "A Technical Blog about Computer Science"


[[resources]]
	src = "static/cv.pdf"
